### ISSUE TITLE
Support Python 2.7

### ISSUE THREAD

**Issue by sprin** [sprin/pg-discuss#8]
The app was developed with the intent of single-source Python 2/3 compatibility. However, Travis (#1) caught a Python 2 error:

```
Traceback (most recent call last):

  File "main.py", line 3, in <module>

    app = app_factory()

  File "/home/travis/build/sprin/pg-discuss/pg_discuss/app.py", line 90, in app_factory

    app.comment_renderer = app.comment_renderer_loader.driver(app)

  File "/home/travis/build/sprin/pg-discuss/blessed_extensions/markdown_renderer.py", line 36, in __init__

    render_flags_int = _compat.reduce(operator.or_,

AttributeError: 'module' object has no attribute 'reduce'
```

We need to fix all Python 2 errors and get the build passing under Travis.

**Comment by sprin** [comment]
Python 2.7 build is passing now.
